import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer/footer";
import Nabvar from "@/components/navbar/navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* bg-[url('/image/fondo.jpg')] bg-cover bg-center  bg-fixed */}
      <body className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased `}>
        <header>
            <Nabvar/>
        </header>
        <main className = "flex-1">
            {children}
        </main>
        <footer>
            <Footer/>
        </footer>
      </body>
    </html>
  );
}
